# Generated by Django 3.1.2 on 2020-10-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rumah_Sakit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=100)),
                ('nama_rs', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=1000)),
                ('telepon', models.IntegerField()),
                ('website', models.CharField(max_length=1000)),
            ],
        ),
    ]
