# Generated by Django 2.1.4 on 2021-01-02 07:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengomentar', models.CharField(max_length=400)),
                ('komen', models.TextField(max_length=800)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.TextField(default='Depok', max_length=400)),
                ('email', models.EmailField(default='gilang.catur@ui.ac.id', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='pertanyaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penanya', models.CharField(max_length=400)),
                ('pertanyaan', models.TextField(max_length=800)),
                ('location', models.TextField(default='Depok', max_length=400)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(default='gilangcaturyudistira@gmail.com', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='komentar',
            name='tanya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.pertanyaan'),
        ),
    ]
