# Generated by Django 3.1.2 on 2020-10-26 05:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pertanyaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penanya', models.CharField(max_length=400)),
                ('judul', models.CharField(max_length=400)),
                ('pertanyaan', models.TextField(max_length=800)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengomentar', models.CharField(max_length=400)),
                ('komen', models.TextField(max_length=800)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.pertanyaan')),
            ],
        ),
    ]
