# Generated by Django 3.1.2 on 2020-12-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20201120_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertanyaan',
            name='email',
            field=models.EmailField(default='gilangcaturyudistira@gmail.com', max_length=254),
        ),
    ]
