# Generated by Django 3.1.2 on 2021-01-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_pengguna_namalengkap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='main.pengguna')),
                ('liked', models.ManyToManyField(blank=True, default=None, related_name='liked', to='main.Pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Skip deh...', 'Skip deh...'), ('Boleh tuh!', 'Boleh tuh!')], default='Boleh tuh!', max_length=30)),
                ('alternatives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_protocol.alternative')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
            ],
        ),
    ]
