# Generated by Django 3.1.2 on 2020-12-21 11:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_pengguna_namalengkap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('pengguna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('alternatives', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_protocol.alternatives')),
                ('pengguna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
            ],
        ),
    ]
