# Generated by Django 3.1.2 on 2021-01-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_protocol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='value',
            field=models.CharField(choices=[('Boleh tuh!', 'Boleh tuh!'), ('Skip deh...', 'Skip deh...')], default='Boleh tuh!', max_length=30),
        ),
    ]
