# Generated by Django 3.1.2 on 2021-01-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_protocol', '0002_auto_20210102_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='value',
            field=models.CharField(choices=[('Skip deh...', 'Skip deh...'), ('Boleh tuh!', 'Boleh tuh!')], default='Boleh tuh!', max_length=30),
        ),
    ]
