# Generated by Django 3.1.2 on 2020-12-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pengguna'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='namalengkap',
            field=models.CharField(default='gilang', max_length=100),
            preserve_default=False,
        ),
    ]
