# Generated by Django 3.1.2 on 2020-11-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tempat', models.CharField(max_length=100)),
                ('tanggal_pelaksanaan_mulai', models.DateField(null=True)),
                ('tanggal_pelaksanaan_akhir', models.DateField(null=True)),
                ('biaya', models.DecimalField(decimal_places=3, max_digits=6)),
                ('alamat', models.TextField()),
            ],
        ),
    ]
